class WorkshopPoll extends HTMLElement {
  connectedCallback(){
    if(this.shadowRoot)return;
    const guide=this.getAttribute('guide')||'default',key=`workshop-poll:${guide}`,presenter=this.getAttribute('mode')==='presenter';
    const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const statusLabel={done:'Положительно',question:'Есть вопрос',problem:'Негативно'};
    const initials=name=>(name.trim().split(/\s+/).map(part=>part[0]).join('').slice(0,2)||'У').toUpperCase();
    const tokenKey='workshop-voter-token';let voterToken=localStorage.getItem(tokenKey);if(!voterToken){voterToken=crypto.randomUUID?.()||Math.random().toString(36).slice(2);localStorage.setItem(tokenKey,voterToken)}
    this.attachShadow({mode:'open'});
    this.shadowRoot.innerHTML=`<style>
      :host{display:block;height:100%;font-family:Inter,Arial,sans-serif;color:#080808}*{box-sizing:border-box}.box{border:2px solid #080808;background:#fff;padding:14px}.box.presenter{display:flex;height:100%;min-height:0;flex-direction:column;border:0;background:transparent;padding:0}.title{font:800 11px/1 monospace;letter-spacing:.07em;text-transform:uppercase}.presenter>.title{display:none}.bars{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.presenter>.bars{margin-top:0}.metric,.vote{min-height:58px;border:1px solid #080808;background:#ecebe6;padding:7px 4px;text-align:center;font:750 11px/1.12 Arial}.vote{cursor:pointer}.done{border-bottom:6px solid #159657}.question{border-bottom:6px solid #858585}.problem{border-bottom:6px solid #e14b3b}.count{display:block;margin-top:5px;font:850 20px/1 monospace}.participant{display:grid;gap:8px;margin-top:10px}.participant input,.participant textarea{width:100%;border:1px solid #080808;background:#fff;padding:9px;font:600 13px/1.3 Arial}.participant textarea{min-height:68px;resize:vertical}.filters{display:flex;gap:4px;flex-wrap:wrap;margin:9px 0 5px}.filter{border:1px solid #aaa;border-radius:15px;background:#fff;padding:5px 8px;font:700 10px/1 Arial;cursor:pointer}.filter.active{border-color:#080808;background:#080808;color:#fff}.filter-count{color:#64645f}.filter.active .filter-count{color:inherit}.log-title{margin:5px 0 0;padding:8px 0 5px;border-top:1px solid #080808;font:800 10px/1 monospace;text-transform:uppercase}.events{min-height:0;margin:0;padding:0;list-style:none;overflow:auto}.presenter .events{flex:1}.event{display:grid;grid-template-columns:26px minmax(0,1fr) 34px;gap:7px;padding:7px 0;border-top:1px solid #c7c7c7}.avatar{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#deddd8;font:800 9px/1 monospace}.who{font-size:12px;font-weight:850}.action{margin-top:2px;color:#64645f;font-size:10px}.badge{display:inline-block;margin-left:4px;padding:2px 4px;border:1px solid currentColor;font:750 9px/1 Arial}.badge.done{color:#0a8f4a;border-bottom-width:1px}.badge.question{color:#666;border-bottom-width:1px}.badge.problem{color:#d53b2d;border-bottom-width:1px}.event time{padding-top:2px;color:#64645f;font:700 9px/1 monospace;text-align:right}.comment{margin:4px 0 0;padding:5px 7px;border-left:2px solid #bbb;background:rgba(255,255,255,.62);font-size:11px;line-height:1.28;overflow-wrap:anywhere}.comment.collapsed{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden}.expand{margin-top:4px;border:0;background:none;padding:0;color:#3152e8;font:750 10px/1 Arial;cursor:pointer}.events .empty{display:block;padding:12px 0;color:#64645f;font-size:12px}.note{margin:7px 0 0;color:#64645f;font:10px/1.2 Arial}.presenter .note{flex:0 0 auto}
    </style><div class="box${presenter?' presenter':''}"><div class="title">Голосование</div><div class="bars"><div class="metric done">Готово<span class="count" data-count="done">0</span></div><div class="metric question">Есть вопрос<span class="count" data-count="question">0</span></div><div class="metric problem">Есть проблема<span class="count" data-count="problem">0</span></div></div>${presenter?'<div class="filters"><button class="filter active" data-filter="all">Все · <span class="filter-count" data-filter-count="all">0</span></button><button class="filter" data-filter="done">Положительно · <span class="filter-count" data-filter-count="done">0</span></button><button class="filter" data-filter="question">Есть вопросы · <span class="filter-count" data-filter-count="question">0</span></button><button class="filter" data-filter="problem">Негативно · <span class="filter-count" data-filter-count="problem">0</span></button><button class="filter" data-filter="comments">Комментарии · <span class="filter-count" data-filter-count="comments">0</span></button></div><div class="log-title">События участников</div><ul class="events"></ul>':'<div class="participant"><input class="nickname" maxlength="32" aria-label="Короткий ник" placeholder="Как вас показать? Например, Алекс"><textarea class="comment-input" maxlength="1000" aria-label="Комментарий" placeholder="Комментарий, если он нужен"></textarea><div class="bars"><button class="vote done" data-vote="done">Я сделал</button><button class="vote question" data-vote="question">Есть вопрос</button><button class="vote problem" data-vote="problem">Есть проблема</button></div></div>'}<p class="note">${presenter?'Локальный прототип. Общий realtime-лог появится после подключения backend.':'Ник и ответ сохраняются только на этом устройстве.'}</p></div>`;
    let filter='all';
    const load=()=>{
      let raw={};try{raw=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
      const legacyCounts=raw.legacyCounts||{done:Number(raw.done)||0,question:Number(raw.question)||0,problem:Number(raw.problem)||0};
      const voters=raw.voters&&typeof raw.voters==='object'?raw.voters:{};
      const events=Array.isArray(raw.events)?raw.events.map((item,index)=>({id:item.id||`legacy-${index}`,type:item.type||'status',status:item.status||item.vote||'question',nickname:item.nickname||'Участник',comment:item.comment||'',time:item.time||'',fromStatus:item.fromStatus||''})):[];
      return{legacyCounts,voters,events};
    };
    const save=data=>{localStorage.setItem(key,JSON.stringify(data));window.dispatchEvent(new CustomEvent('workshop-poll-update',{detail:{guide}}))};
    const counts=data=>{const result={...data.legacyCounts};Object.values(data.voters).forEach(voter=>{if(result[voter.status]!==undefined)result[voter.status]+=1});return result};
    const eventHtml=item=>{
      const long=item.comment.length>120,eventId=esc(item.id),action=item.type==='comment'?'оставил комментарий':item.fromStatus?'сменил статус':'выбрал статус';
      return `<li class="event" data-status="${esc(item.status)}"><span class="avatar">${esc(initials(item.nickname))}</span><div><div class="who">${esc(item.nickname)}</div><div class="action">${action}<span class="badge ${esc(item.status)}">${esc(statusLabel[item.status]||item.status)}</span></div>${item.comment?`<div class="comment${long?' collapsed':''}" data-comment="${eventId}">${esc(item.comment)}</div>${long?`<button class="expand" type="button" data-expand="${eventId}">Показать полностью</button>`:''}`:''}</div><time>${esc(item.time)}</time></li>`;
    };
    const draw=()=>{
      const data=load(),currentCounts=counts(data);Object.entries(currentCounts).forEach(([status,value])=>{const node=this.shadowRoot.querySelector(`[data-count="${status}"]`);if(node)node.textContent=value});
      const current=data.voters[voterToken];if(!presenter){const nickname=this.shadowRoot.querySelector('.nickname');if(!nickname.value)nickname.value=current?.nickname||localStorage.getItem('workshop-poll-name')||''}
      this.shadowRoot.querySelectorAll('[data-filter-count]').forEach(node=>{const type=node.dataset.filterCount;node.textContent=type==='all'?data.events.length:type==='comments'?data.events.filter(item=>item.comment).length:data.events.filter(item=>item.status===type).length});const eventsNode=this.shadowRoot.querySelector('.events');if(eventsNode){const visible=data.events.filter(item=>filter==='all'||filter==='comments'&&item.comment||item.status===filter);eventsNode.innerHTML=visible.length?visible.slice().reverse().map(eventHtml).join(''):'<li class="empty">По этому фильтру событий пока нет</li>'}
      this.dispatchEvent(new CustomEvent('poll-change',{bubbles:true,composed:true,detail:currentCounts}));
    };
    this.shadowRoot.addEventListener('click',event=>{
      const filterButton=event.target.closest('[data-filter]');if(filterButton){filter=filterButton.dataset.filter;this.shadowRoot.querySelectorAll('[data-filter]').forEach(button=>button.classList.toggle('active',button===filterButton));draw();return}
      const expand=event.target.closest('[data-expand]');if(expand){const comment=this.shadowRoot.querySelector(`[data-comment="${CSS.escape(expand.dataset.expand)}"]`),collapsed=comment.classList.toggle('collapsed');expand.textContent=collapsed?'Показать полностью':'Свернуть';return}
      const vote=event.target.closest('[data-vote]');if(!vote)return;const data=load(),nickname=(this.shadowRoot.querySelector('.nickname').value.trim()||'Участник').slice(0,32),comment=this.shadowRoot.querySelector('.comment-input').value.trim(),status=vote.dataset.vote,previous=data.voters[voterToken];localStorage.setItem('workshop-poll-name',nickname);data.voters[voterToken]={status,nickname,updatedAt:new Date().toISOString()};const time=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});if(!previous||previous.status!==status||comment)data.events.push({id:crypto.randomUUID?.()||Math.random().toString(36).slice(2),type:previous&&previous.status===status?'comment':'status',fromStatus:previous?.status||'',status,nickname,comment,time});data.events=data.events.slice(-100);this.shadowRoot.querySelector('.comment-input').value='';save(data);draw();
    });
    window.addEventListener('workshop-poll-update',event=>{if(event.detail.guide===guide)draw()});window.addEventListener('storage',event=>{if(event.key===key)draw()});draw();setTimeout(draw,0);
  }
}
customElements.define('workshop-poll',WorkshopPoll);
